### ISSUE TITLE
Question about schemas for `wires.in.purchase-item-events/PurchaseItemCreatedEvent`

### ISSUE THREAD

**Issue by macielti** [gumberss/PurchaseListinator#129]
For this [adapter](https://github.com/gumberss/PurchaseListinator/blob/88e07314047d5b1a667217effe49f20511d5f2e8/src/purchase_listinator/adapters/in/shopping_purchase_list_events.clj#L19-L23)
It expects the output (models.internal.shopping-cart/PurchaseListItemCreated) to contain a `:shopping-id`, but the schema (wires.in.purchase-item-events/PurchaseItemCreatedEvent) for the input of the adapter doesn't contain it.
Should we add the `:shopping-id` property for the input schema (wires.in.purchase-item-events/PurchaseItemCreatedEvent)?

**Comment by gumberss** [comment]
No, the shopping-id doesn't come in the wire, we need to get it directly from the database when this event came 

![image](https://github.com/gumberss/PurchaseListinator/assets/38296002/2c9e5084-9df9-4b38-9186-610e207a135c)
![image](https://github.com/gumberss/PurchaseListinator/assets/38296002/9799bcd2-978a-412a-bc45-5068827fbda7)

Probably I forgot to adjust some schemas like this one. Thank you for your help finding some of them :D

**Comment by macielti** [comment]
I have submitted a [pull request](https://github.com/gumberss/PurchaseListinator/pull/128) proposing to make the `:shopping-id` field optional. What do you think?
