### ISSUE TITLE
[Question] The wire entity must have `UUID` as `String`?

### ISSUE THREAD

**Issue by macielti** [gumberss/PurchaseListinator#131]
Does we need to convert the purchase-list Id from `UUID` to `String` in this [adapter](https://github.com/macielti/PurchaseListinator/blob/94a2ae9283c4fb970dd6c0f49eff48ed6cfd379c/src/purchase_listinator/adapters/out/purchase_list.clj#L6-L9)?
I am asking because the [schema for the output](https://github.com/macielti/PurchaseListinator/blob/9be72da5385a11daa684bff2ebc6d74889b33bdf/src/purchase_listinator/wires/purchase_list/out/purchase_list.clj#L5-L7) expects the Id to be an `UUID` but the adapter is parsing it to `String`. Should it really be a `String`?

**Comment by gumberss** [comment]
It depends on where the wire will be used, for rabbitmq events, there is a coerce already implemented and this conversion is not needed. If the wire is used in a pedestal endpoint, the conversion is needed. 
In this case, the schema is used in the pedestal endpoint, so we need to parse it to string, so probably the schema is wrong :/
